export const GET_BEERS = 'GET_BEERS'
export const GET_BEERS_SUCCESS = 'GET_BEERS_SUCCESS'
export const GET_BEERS_FAIL = 'GET_BEERS_FAIL'

export const GET_BEER_INFO = 'GET_BEER_INFO'
export const GET_BEER_INFO_SUCCESS = 'GET_BEER_INFO_SUCCESS'
export const GET_BEER_INFO_FAIL = 'GET_BEER_INFO_FAIL'

export const GET_MORE_BEERS = 'GET_MORE_BEERS'
export const GET_MORE_BEERS_SUCCESS = 'GET_MORE_BEERS_SUCCESS'
export const GET_MORE_BEERS_FAIL = 'GET_MORE_BEERS_FAIL'